name: Build and Deploy
on:
  push:
    branches: [main]
  schedule:
    - cron: "17 3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python scripts/build.py
      - name: Build site
        run: |
          npm ci
          npm run build
      - name: Deploy to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/.vitepress/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
